[[fields]]
name = "id"
size = 4

[[fields]]
name = "first_name"
size = 255

[[fields]]
name = "last_name"
size = 255

[[fields]]
name = "age"
size = 1

[[queries]]
order_by = [["age", false]]
[queries.where]
operator = "and"
[[queries.where.values]]
operator = "="
column = "first_name"
value = "John"
[[queries.where.values]]
operator = "="
column = "last_name"
value = "Brack"
[[queries.where.values]]
operator = ">"
column = "age"
value = 25
